# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Environmental variables
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: gradle:6-jdk11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone-down
        uses: actions/checkout@v3   

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: chmod +x ci/build-app.sh && ci/build-app.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CompiledCode
          path: app/build/libs/app-0.1-all.jar
  
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    
    steps:
      # Downloads the artifact from the build step 
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: CompiledCode
          path: app/build/libs/app-0.1-all.jar

      - name: build docker
        run: chmod +x ci/build-docker.sh && ci/build-docker.sh
        
      - name: push docker
        run: chmod +x ci/push-docker.sh && ci/push-docker.sh
        
      
